// imageData.js

const imageData = {
    January2023: [
      '/images/image1.jpeg',
      '/images/image2.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      // Add more images
    ],
    February2023: [
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      '/images/image3.jpg',
      '/images/image4.jpeg',
      // Add more images
    ],
      
    March2023: [
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        // Add more images
      ],

    May2023: [
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        // Add more images
      ],

      
    June2023: [
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        // Add more images
      ],
      
    July2023: [
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        // Add more images
      ],
      
    August2023: [
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        // Add more images
      ],
      
    September2023: [
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        // Add more images
      ],
      
    October2023: [
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        // Add more images
      ],
      
    November2023: [
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        // Add more images
      ],
      
    December2023: [
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        '/images/image3.jpg',
        '/images/image4.jpeg',
        // Add more images
      ],
    // Add more months and images as needed
  };
  
  export default imageData;
  